name: 'actions'

on: ['push', 'pull_request']

jobs:
  run:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: 'Install dependencies'
        uses: npm install
      - name: 'Run tests'
        uses: npm run test
      # - name: 'Test coverage'
      #   uses: 'codecov/codecov-action@v4.0.1'
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: 'IoannP/npm-info'
